name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: node:22-bookworm
    steps:
      - name: Checkout
        env:
          GITEA_TOKEN: ${{ github.token }}
          REPOSITORY_URL: http://10.144.144.2:3333/yunhai/GlobalCityReview.git
        run: |
          git config --global init.defaultBranch main
          git init .
          git remote add origin "${REPOSITORY_URL}"
          git -c http.extraheader="Authorization: token ${GITEA_TOKEN}" fetch --depth=1 origin "${{ github.sha }}"
          git checkout --detach FETCH_HEAD

      - name: Install dependencies
        run: npm install

      - name: Install Bun
        run: npm install --global bun

      - name: Deploy
        run: npm run cf:deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
